mainSections:
  - post
  - projects
rssFullContent: true
favicon: "/favicon.svg"
featuredImageField: "image"

footer:
  since: 2024
  customText: ""

dateFormat:
  published: "Jan 02, 2006"
  lastUpdated: "Jan 02, 2006 15:04 IST"

sidebar:
  emoji: ""
  subtitle: "Loves poha a lot!"
  compact: false
  avatar:
    enabled: true
    local: true
    src: "img/avatar.jpg"

article:
  headingAnchor: false
  math: false
  readingTime: false
  toc: true
  license:
    enabled: false
    default: "Licensed under CC BY-NC-SA 4.0"

widgets:
  homepage:
    # - type: "search"
    - type: "archives"
      params:
        limit: 5
    - type: "categories"
      params:
        limit: 10
    - type: "tag-cloud"
      params:
        limit: 10
  page:
    - type: "toc"

opengraph:
  twitter:
    site: "jhalani_shivang"
    card: "summary_large_image"

defaultImage:
  opengraph:
    enabled: true
    local: true
    src: "img/avatar.jpg"

colorScheme:
  toggle: true
  default: "dark"

imageProcessing:
  cover:
    enabled: true
  content:
    enabled: true

comments:
  enabled: true
  provider: "giscus"
  disqusjs:
    shortname: ""
    apiUrl: ""
    apiKey: ""
    admin: ""
    adminLabel: ""
  utterances:
    repo: ""
    issueTerm: "pathname"
    label: ""
  remark42:
    host: ""
    site: ""
    locale: ""
  vssue:
    platform: ""
    owner: ""
    repo: ""
    clientId: ""
    clientSecret: ""
    autoCreateIssue: false
  waline:
    serverURL: ""
    lang: ""
    visitor: ""
    avatar: ""
    emoji:
      - "https://cdn.jsdelivr.net/gh/walinejs/emojis/weibo"
    requiredMeta:
      - "name"
      - "email"
      - "url"
    placeholder: ""
    locale:
      admin: "Admin"
  twikoo:
    envId: ""
    region: ""
    path: ""
    lang: ""
  cactus:
    defaultHomeserverUrl: "https://matrix.cactus.chat:8448"
    serverName: "cactus.chat"
    siteName: ""
  giscus:
    repo: "shivangjhalani/shivangjhalani.com"
    repoID: "R_kgDONXOiXg"
    category: "Announcements"
    categoryID: "DIC_kwDONXOiXs4Ckxir"
    mapping: "pathname"
    inputPosition: "top"
    lightTheme: "light"
    darkTheme: "dark_dimmed"
    reactionsEnabled: 1
    emitMetadata: 0
  gitalk:
    owner: ""
    admin: ""
    repo: ""
    clientID: ""
    clientSecret: ""
  cusdis:
    host: ""
    id: ""
